In [58]:
import cv2
import numpy as np
import math
import glob

In [ ]:
vid = cv2.VideoCapture(glob.glob("*sink.mp4")[0])
ret, frame = vid.read()
cv2.imwrite("frame.jpg", frame)

cv2.imshow('calibrated', frame)
cv2.waitKey(0)
cv2.destroyAllWindows()

# known corners
width = frame.shape[1]
height = frame.shape[0]

tl = [285,248]
tr = [509, 249]


br = [581, 312]
bl = [226, 307]

tl, tr, br, bl

# Computing Destination Points

tl_x, tl_y = tl[0], tl[1]
tr_x, tr_y = tr[0], tr[1]
bl_x, bl_y = bl[0], bl[1]

obj_width = math.sqrt(((tr_x - tl_x)**2) + ((tr_y - tl_y)**2))
obj_height = math.sqrt(((tl_x - bl_x)**2) + ((bl_y - tl_y)**2))


obj_width, obj_height
tl_dest = tl.copy()
tr_dest = np.array([tl_dest[0]+obj_width, tl_dest[1]])
bl_dest = np.array([tl_dest[0], tl_dest[1]+ obj_height]) 
br_dest = np.array([tr_dest[0], tl_dest[1]+obj_height])

dest_four_corners = np.float32([tl_dest, tr_dest, br_dest, bl_dest])
dest_four_corners


known_four_corners = np.float32([tl, tr, br, bl])

for corner in known_four_corners:
    cv2.circle(frame, [round(corner[0]), round(corner[1])], 5, [255,0,0], 2)
    cv2.imshow('img', frame)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
P = cv2.getPerspectiveTransform(known_four_corners, dest_four_corners)
img_transformed = cv2.warpPerspective(img, P, (int(width), int(height)))

cv2.imshow('transformed',img_transformed)
cv2.waitKey(0)
cv2.destroyAllWindows() 
vid.release()

In [45]:
img = cv2.imread('calibratedresult.png', cv2.IMREAD_GRAYSCALE)
PATTERN_SIZE = (9,6)
criteria = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 1e-3)

res, corners = cv2.findChessboardCorners(img, PATTERN_SIZE)
corners = cv2.cornerSubPix(img, corners, (10,10), (-1,-1), criteria)

In [46]:
#cv2.drawChessboardCorners(img, PATTERN_SIZE, corners, res)
cv2.imshow('calibrated', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [47]:
# known corners
width = img.shape[1]
height = img.shape[0]

tl = corners[45][0]
tr = corners[0][0]
br = corners[8][0]
bl = corners[-1][0]

tl, tr, br, bl


(array([228.54092,  76.65305], dtype=float32),
 array([402.0541  ,  67.279686], dtype=float32),
 array([425.83682, 364.48828], dtype=float32),
 array([201.12828, 366.69318], dtype=float32))

In [48]:


# Computing Destination Points

tl_x, tl_y = tl[0], tl[1]
tr_x, tr_y = tr[0], tr[1]
bl_x, bl_y = bl[0], bl[1]

obj_width = math.sqrt(((tr_x - tl_x)**2) + ((tr_y - tl_y)**2))
obj_height = math.sqrt(((tl_x - bl_x)**2) + ((bl_y - tl_y)**2))


obj_width, obj_height
tl_dest = tl.copy()
tr_dest = np.array([tl_dest[0]+obj_width, tl_dest[1]])
bl_dest = np.array([tl_dest[0], tl_dest[1]+ obj_height]) 
br_dest = np.array([tr_dest[0], tl_dest[1]+obj_height])

dest_four_corners = np.float32([tl_dest, tr_dest, br_dest, bl_dest])
dest_four_corners



array([[228.54092,  76.65305],
       [402.3071 ,  76.65305],
       [402.3071 , 367.98575],
       [228.54092, 367.98575]], dtype=float32)

In [49]:
known_four_corners = np.float32([tl, tr, br, bl])

for corner in known_four_corners:
    cv2.circle(img, [round(corner[0]), round(corner[1])], 5, [255,0,0], 2)
    cv2.imshow('img', img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [50]:
#cv2.imwrite('image_calibrated_four_points_selected.png', img)

In [51]:

P = cv2.getPerspectiveTransform(known_four_corners, dest_four_corners)
img_transformed = cv2.warpPerspective(img, P, (int(width), int(height)))

In [52]:
cv2.imshow('transformed',img_transformed)
cv2.waitKey(0)
cv2.destroyAllWindows() 



In [53]:
#cv2.imwrite('image_calibrated_warped.png', img_transformed)